# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Machine learning
email: oneata@eloquentix.com
description: > # this means to ignore newlines until "baseurl:"
  A short introductory machine learning course offered by the SpeeD laboratory
  (Polytechnic University of Bucharest).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://speed-ml.github.io" # the base hostname & protocol for your site
permalink: /:title.html

# Build settings
markdown: kramdown

sass:
  # loading path from site root
  # default to _sass
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  style: compressed
